import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.MvPolynomial.MonomialOrder

open MvPolynomial MonomialOrder
open scoped MonomialOrder

variable {σ R : Type*} [CommSemiring R]
variable {k : Type*} [Field k]
variable {m : MonomialOrder σ}

namespace MonomialOrder

variable (m) in
/-- the leading coefficient of a multivariate polynomial with respect
to a monomial ordering -/
noncomputable def leadingTerm (f : MvPolynomial σ R) : MvPolynomial σ R :=
  monomial (m.degree f) (m.leadingCoeff f)

variable (m) in
/-- The set of leading terms of nonzero polynomials in an ideal I. -/
def LT_set (I : Ideal (MvPolynomial σ R)) : Set (MvPolynomial σ R) :=
  { f | ∃ g ∈ I, g ≠ 0 ∧ leadingTerm m g = f }

variable (m) in
def leadingTermIdeal (I : Ideal (MvPolynomial σ R)) : Ideal (MvPolynomial σ R) :=
  Ideal.span (LT_set m I)

end MonomialOrder

namespace MvPolynomial

variable (m) in
def IsGroebnerBasis (I : Ideal (MvPolynomial σ k)) (G : Finset (MvPolynomial σ k)) : Prop :=
  (G : Set (MvPolynomial σ k)) ⊆ I ∧
  Ideal.span ((fun g => leadingTerm m g) '' (G : Set (MvPolynomial σ k))) = leadingTermIdeal m I

variable [Fintype σ] in
/--
Ch.2 §5, Exercise 10.

If `I` is principal (generated by a single `f`) and a finite set `G ⊆ I`
contains a generator of `I`, then `G` is a Gröbner basis of `I`.
-/
example
    {I : Ideal (MvPolynomial σ k)}
    (hI : I.IsPrincipal)
    {G : Finset (MvPolynomial σ k)}
    (hGI : (G : Set (MvPolynomial σ k)) ⊆ I)
    (hgen : ∃ f : MvPolynomial σ k, f ∈ G ∧ I = Ideal.span ({f} : Set (MvPolynomial σ k))) :
    IsGroebnerBasis (m := m) I G := by
  sorry

end MvPolynomial
