import Mathlib
import Buchberger.ReductionRelations

namespace MonomialOrder

open MvPolynomial
open scoped MonomialOrder

variable {σ : Type*} (m : MonomialOrder σ) {K : Type*} [Field K]

/-- One-step reduction modulo `p`, eliminating the term `t`. -/
def ReducesToBy (p f g : MvPolynomial σ K) (t : σ →₀ ℕ) : Prop :=
  p ≠ 0 ∧ t ∈ f.support ∧
    ∃ s : σ →₀ ℕ, s + m.degree p = t ∧
      g = f - monomial s (f.coeff t / m.leadingCoeff p) * p

/-- One-step reduction modulo a single polynomial `p`. -/
def ReducesToPoly (p f g : MvPolynomial σ K) : Prop :=
  ∃ t : σ →₀ ℕ, m.ReducesToBy p f g t

/-- One-step reduction modulo a set `P`. -/
def ReducesToSet (P : Set (MvPolynomial σ K)) (f g : MvPolynomial σ K) : Prop :=
  ∃ p ∈ P, m.ReducesToPoly p f g

/-- Reducibility modulo a single polynomial. -/
def Reducible (p f : MvPolynomial σ K) : Prop :=
  ∃ g, m.ReducesToPoly p f g

/-- Reducibility modulo a set. -/
def ReducibleSet (P : Set (MvPolynomial σ K)) (f : MvPolynomial σ K) : Prop :=
  ∃ g, m.ReducesToSet P f g

namespace ReducesToPoly

/-- Normal form modulo a single polynomial. -/
abbrev NormalForm (p f : MvPolynomial σ K) : Prop :=
  Relation.IsNormalForm (m.ReducesToPoly p) f

/--
Lemma 5.20(i).

A polynomial `f` is reducible modulo `p` iff `p ≠ 0` and some term of `f`
is divisible by the leading monomial of `p`.

Here divisibility of monomials is written additively as
`∃ s, s + m.degree p = t`.
-/
theorem reducible_iff_exists_add_degree
    (p f : MvPolynomial σ K) :
    m.Reducible p f ↔
      p ≠ 0 ∧ ∃ t ∈ f.support, ∃ s : σ →₀ ℕ, s + m.degree p = t := by
  constructor
  · rintro ⟨g, t, hp, ht, s, hs, _hg⟩
    exact ⟨hp, t, ht, s, hs⟩
  · rintro ⟨hp, t, ht, s, hs⟩
    refine ⟨f - monomial s (f.coeff t / m.leadingCoeff p) * p, t, hp, ht, s, hs, rfl⟩

end ReducesToPoly

namespace ReducesToSet

/-- Reflexive-transitive closure of one-step reduction modulo `P`. -/
abbrev ReflTransGen (P : Set (MvPolynomial σ K)) :
    MvPolynomial σ K → MvPolynomial σ K → Prop :=
  Relation.ReflTransGen (m.ReducesToSet P)

/-- Equivalence closure generated by one-step reduction modulo `P`. -/
abbrev EqvGen (P : Set (MvPolynomial σ K)) :
    MvPolynomial σ K → MvPolynomial σ K → Prop :=
  Relation.EqvGen (m.ReducesToSet P)

/-- Joinability modulo `P`. -/
abbrev Join (P : Set (MvPolynomial σ K)) :
    MvPolynomial σ K → MvPolynomial σ K → Prop :=
  Relation.Join (Relation.ReflTransGen (m.ReducesToSet P))

/-- Normal form modulo a set `P`. -/
abbrev NormalForm (P : Set (MvPolynomial σ K)) (f : MvPolynomial σ K) : Prop :=
  Relation.IsNormalForm (m.ReducesToSet P) f

end ReducesToSet


/--
A monomial order equipped with the induced well-order on finite sets of terms.

In Becker--Weispfenning--Kredel, this is the extension

`T ⟶ P_fin(T) ⟶ R[X]`.
-/
structure WithSupportOrder (σ : Type*) extends MonomialOrder σ where
  /-- The induced linear order on finite sets of terms. -/
  finsetLO : LinearOrder (Finset syn)

  /-- The induced order on finite sets of terms is well-founded. -/
  finsetWF : @WellFoundedLT (Finset syn) finsetLO.toLT

  /--
  Characterization of the strict induced order on finite sets:
  `s < t` iff the maximum term of the symmetric difference belongs to `t`.
  -/
  finset_lt_iff :
    ∀ s t : Finset syn,
      letI := lo
      letI := finsetLO
      s < t ↔
        ∃ h : (symmDiff s t).Nonempty,
          (symmDiff s t).max' h ∈ t



namespace Relation

variable {α : Type*}

/--
If a relation `r` is contained in the inverse of a well-founded relation `lt`,
then `flip r` is well-founded.

This is the abstract form used to prove termination of reduction relations.
-/
theorem wellFounded_flip_of_subrelation
    {r lt : α → α → Prop}
    (hlt : WellFounded lt)
    (hsub : ∀ {a b : α}, r a b → lt b a) :
    WellFounded (flip r) := by
  exact hlt.mono fun a b h => hsub h

/--
A relation whose inverse is well-founded is asymmetric.
-/
theorem asymm_of_wellFounded_flip
    {r : α → α → Prop}
    (h : WellFounded (flip r)) :
    Std.Asymm r := by
  constructor
  intro a b hab hba
  revert b
  induction h.apply a with
  | intro a acc ih =>
      intro b hab hba
      exact (ih b hab a hba) hab

end Relation


namespace ReducesToSet

/--
Lemma 5.20(iv), lifted from reduction modulo a single polynomial to reduction
modulo a set.

Once the induced polynomial order `lt` is defined, the hypothesis `hpoly`
is exactly the statement that a one-step reduction modulo a single polynomial
strictly decreases that order.
-/
theorem decreases_of_reducesToPoly_decreases
    {lt : MvPolynomial σ K → MvPolynomial σ K → Prop}
    (hpoly :
      ∀ {p f g : MvPolynomial σ K},
        m.ReducesToPoly p f g → lt g f)
    {P : Set (MvPolynomial σ K)} {f g : MvPolynomial σ K}
    (h : m.ReducesToSet P f g) :
    lt g f := by
  rcases h with ⟨p, _hpP, hpfg⟩
  exact hpoly hpfg

/--
Theorem 5.21, abstract termination form.

If every one-step reduction modulo `P` strictly decreases a well-founded
polynomial order `lt`, then the reduction relation modulo `P` is well-founded.
-/
theorem wellFounded_of_decreases
    (P : Set (MvPolynomial σ K))
    {lt : MvPolynomial σ K → MvPolynomial σ K → Prop}
    (hlt : WellFounded lt)
    (hred :
      ∀ {f g : MvPolynomial σ K},
        m.ReducesToSet P f g → lt g f) :
    WellFounded (flip (m.ReducesToSet P)) :=
  Relation.wellFounded_flip_of_subrelation hlt hred

/--
Theorem 5.21, asymmetric form.

If every one-step reduction modulo `P` strictly decreases a well-founded
polynomial order, then `m.ReducesToSet P` is asymmetric.

In the terminology of Becker--Weispfenning--Kredel, this says that
`m.ReducesToSet P` is a reduction relation.
-/
theorem asymm_of_decreases
    (P : Set (MvPolynomial σ K))
    {lt : MvPolynomial σ K → MvPolynomial σ K → Prop}
    (hlt : WellFounded lt)
    (hred :
      ∀ {f g : MvPolynomial σ K},
        m.ReducesToSet P f g → lt g f) :
    Std.Asymm (m.ReducesToSet P) :=
  Relation.asymm_of_wellFounded_flip
    (wellFounded_of_decreases m P hlt hred)

/--
Theorem 5.21 packaged form.

This is the formal version of: reduction modulo `P` is a noetherian
reduction relation.
-/
theorem noetherian_reduction_of_decreases
    (P : Set (MvPolynomial σ K))
    {lt : MvPolynomial σ K → MvPolynomial σ K → Prop}
    (hlt : WellFounded lt)
    (hred :
      ∀ {f g : MvPolynomial σ K},
        m.ReducesToSet P f g → lt g f) :
    WellFounded (flip (m.ReducesToSet P)) ∧ Std.Asymm (m.ReducesToSet P) := by
  have hwf : WellFounded (flip (m.ReducesToSet P)) :=
    wellFounded_of_decreases m P hlt hred
  exact ⟨hwf, Relation.asymm_of_wellFounded_flip hwf⟩

end ReducesToSet







/-- Normal form modulo a single polynomial. -/
abbrev NormalFormMod (p f : MvPolynomial σ K) : Prop :=
  ReducesToPoly.NormalForm m p f

/-- Normal form modulo a set `P`. -/
abbrev NormalFormModSet (P : Set (MvPolynomial σ K)) (f : MvPolynomial σ K) : Prop :=
  ReducesToSet.NormalForm m P f

/-- Top-reduction modulo `p`. -/
def TopReduces (p f g : MvPolynomial σ K) : Prop :=
  m.ReducesToBy p f g (m.degree f)


/-- Helper for the Translation Lemma: single-step translation. -/
lemma translation_single_step (P : Set (MvPolynomial σ K))
    (f g h h₁ : MvPolynomial σ K) (hfgh : f - g = h)
    (hh₁ : m.ReducesToSet P h h₁) :
    ∃ f₁ g₁ : MvPolynomial σ K,
      f₁ - g₁ = h₁ ∧
      ReducesToSet.ReflTransGen m P f f₁ ∧
      ReducesToSet.ReflTransGen m P g g₁ := by
  obtain ⟨p, hpP, t, hp_ne, _ht_supp, s, hs, hh₁_eq⟩ := hh₁
  set b := m.leadingCoeff p with hb_def
  set c₁ := f.coeff t with hc₁_def
  set c₂ := g.coeff t with hc₂_def
  refine ⟨f - monomial s (c₁ / b) * p, g - monomial s (c₂ / b) * p, ?_, ?_, ?_⟩
  · have hc_diff : c₁ - c₂ = h.coeff t := by
      rw [hc₁_def, hc₂_def, ← hfgh, MvPolynomial.coeff_sub]
    have hmono : (monomial s (c₁ / b) - monomial s (c₂ / b) : MvPolynomial σ K)
        = monomial s (h.coeff t / b) := by
      rw [← map_sub, ← sub_div, hc_diff]
    rw [hh₁_eq]
    linear_combination hfgh - p * hmono
  · by_cases hc₁0 : c₁ = 0
    · have hzero : (monomial s (c₁ / b) : MvPolynomial σ K) = 0 := by
        rw [hc₁0, zero_div, (monomial s).map_zero]
      rw [hzero, zero_mul, sub_zero]
    · apply Relation.ReflTransGen.single
      exact ⟨p, hpP, t, hp_ne, MvPolynomial.mem_support_iff.mpr hc₁0, s, hs, rfl⟩
  · by_cases hc₂0 : c₂ = 0
    · have hzero : (monomial s (c₂ / b) : MvPolynomial σ K) = 0 := by
        rw [hc₂0, zero_div, (monomial s).map_zero]
      rw [hzero, zero_mul, sub_zero]
    · apply Relation.ReflTransGen.single
      exact ⟨p, hpP, t, hp_ne, MvPolynomial.mem_support_iff.mpr hc₂0, s, hs, rfl⟩

/-- Translation Lemma, part (i). -/
theorem translation_lemma_i (P : Set (MvPolynomial σ K))
    (f g h h₁ : MvPolynomial σ K) (hfgh : f - g = h)
    (hh₁ : ReducesToSet.ReflTransGen m P h h₁) :
    ∃ f₁ g₁ : MvPolynomial σ K,
      f₁ - g₁ = h₁ ∧
      ReducesToSet.ReflTransGen m P f f₁ ∧
      ReducesToSet.ReflTransGen m P g g₁ := by
  induction hh₁ with
  | refl =>
      exact ⟨f, g, hfgh, Relation.ReflTransGen.refl, Relation.ReflTransGen.refl⟩
  | tail _hstep hlast ih =>
      obtain ⟨f₂, g₂, hsub₂, hf₂, hg₂⟩ := ih
      obtain ⟨f₁, g₁, hsub₁, hf₂f₁, hg₂g₁⟩ :=
        m.translation_single_step P f₂ g₂ _ _ hsub₂ hlast
      exact ⟨f₁, g₁, hsub₁, hf₂.trans hf₂f₁, hg₂.trans hg₂g₁⟩

/-- Translation Lemma, part (ii): joinability. -/
theorem translation_lemma_ii_join (P : Set (MvPolynomial σ K))
    (f g : MvPolynomial σ K)
    (hfg : ReducesToSet.ReflTransGen m P (f - g) 0) :
    ReducesToSet.Join m P f g := by
  obtain ⟨f₁, g₁, hsub, hf, hg⟩ :=
    m.translation_lemma_i P f g (f - g) 0 rfl hfg
  refine ⟨f₁, hf, ?_⟩
  have hgf : g₁ = f₁ := (sub_eq_zero.mp hsub).symm
  rw [hgf] at hg
  exact hg

/-- Translation Lemma, part (ii): equivalence closure. -/
theorem translation_lemma_ii_eqv (P : Set (MvPolynomial σ K))
    (f g : MvPolynomial σ K)
    (hfg : ReducesToSet.ReflTransGen m P (f - g) 0) :
    ReducesToSet.EqvGen m P f g := by
  exact Relation.Join.toEqvGen (m.translation_lemma_ii_join P f g hfg)

end MonomialOrder
