import Mathlib.RingTheory.MvPolynomial.MonomialOrder
import Mathlib.RingTheory.Noetherian.Defs
import Mathlib.RingTheory.Finiteness.Defs

namespace MonomialOrder

open MvPolynomial

variable {σ : Type*} {m : MonomialOrder σ} {R : Type*} [CommSemiring R]

variable (m) in
/-- the leading coefficient of a multivariate polynomial with respect to a monomial ordering -/
noncomputable def leadingTerm (f : MvPolynomial σ R) : MvPolynomial σ R :=
  monomial (m.degree f) (f.coeff (m.degree f))

variable (m) in
/-- The set of leading terms of nonzero polynomials in an ideal I. -/
def leadingTermSet (I : Ideal (MvPolynomial σ R)) : Set (MvPolynomial σ R) :=
  { f | ∃ g ∈ I, g ≠ 0 ∧ leadingTerm m g = f }

variable (m) in
/-- The ideal generated by the leading terms of the nonzero elements of I. -/
def initialIDeal (I : Ideal (MvPolynomial σ R)) : Ideal (MvPolynomial σ R) :=
  Ideal.span (leadingTermSet m I) -- initialIDeal = Ideal.span { f | ∃ g ∈ I, g ≠ 0 ∧ leadingTerm m g = f }

-- Proposition 3.
theorem initialIDeal_is_monomial_ideal {I : Ideal (MvPolynomial σ R)} (hI : I ≠ ⊥) :
  ∃ (A : Finset (σ →₀ ℕ)), (A.toSet ⊆ { s : (σ →₀ ℕ) | ∃ (g : MvPolynomial σ R), g ∈ I ∧ g ≠ 0 ∧ m.degree g = s } ∧
    initialIDeal m I = Ideal.span { f | ∃ s ∈ A, f = monomial s (1 : R) }) := by sorry

/- Definition 5. Groebner_basis
A finite subset G of an ideal I is called a Gröbner basis (or standard basis)
if the ideal generated by the leading terms of the elements of G equals the leading term ideal of I.
We adopt the convention that ⟨∅⟩ = {0}, so that the empty set is the Gröbner basis of the zero ideal.
-/

variable (m) in
def isGrobnerBasis {ι : Type*} (I : Ideal (MvPolynomial σ R)) (G : ι →₀ MvPolynomial σ R) [DecidableEq (MvPolynomial σ R)]: Prop :=
  (I = ⊥ ∧ G = 0) ∨
  (I ≠ ⊥ ∧ (∀ i ∈ G.support, G i ∈ I) ∧
    Ideal.span (G.support.image (fun i ↦ leadingTerm m (G i))) = initialIDeal m I)

/-
Corollary 6.
Fix a monomial order on \(k[x_1,\dots,x_n]\). Then every ideal \(I\) has a Gröbner basis.
Furthermore, any Gröbner basis for \(I\) is a generating set of \(I\).
-/

theorem Hilbert_basis_initial (I : Ideal (MvPolynomial σ R)) [Fintype σ]: Ideal.FG (initialIDeal m I)
  := sorry -- (inferInstance : IsNoetherian _ _).noetherian (initialIDeal m I)

theorem grobner_basis_exists (I : Ideal (MvPolynomial σ R)) [Fintype σ] [DecidableEq (MvPolynomial σ R)]:
  ∃ (ι : Type*) (G : ι →₀ MvPolynomial σ R), isGrobnerBasis m I G := by
  have h_fin : Ideal.FG (initialIDeal m I) := Hilbert_basis_initial I
  sorry
