import SNU.Buchberger.MonomialIdeal
import Mathlib.RingTheory.MvPolynomial.Groebner

variable {σ : Type*}
variable {m : MonomialOrder σ}
variable {k : Type*} [Field k] [DecidableEq k]

open MonomialOrder

namespace MvPolynomial

variable (m) in
/--
**Gröbner basis property.**
For an ideal `I` and a finite set `G`, this means:

- `G ⊆ I`, and
- `⟨ LT(G) ⟩ = ⟨ LT(I) ⟩`,

where `LT(G) = { LT(g) | g ∈ G }` and `LT(I) = { LT(f) | f ∈ I \ {0} }`.
-/
def GroebnerBasis_prop (I : Ideal (MvPolynomial σ k)) (G : Finset (MvPolynomial σ k)) : Prop :=
  (G : Set (MvPolynomial σ k)) ⊆ I ∧
  Ideal.span ((fun g => leadingTerm m g) '' (G : Set (MvPolynomial σ k))) = leadingTermIdeal m I

variable (m) [DecidableEq σ] in
/-- **Cox, Little, O'Shea, Ch 2, §5 Definition 5. Groebner_basis**
A finite subset `G` of an ideal `I` is called a Gröbner basis (or standard basis) if

1. `0 ∉ G`, and
2. `G ⊆ I`, and
3. `⟨ LT(G) ⟩ = ⟨ LT(I) ⟩` (the ideal generated by the leading terms of the elements of `G`
equals the leading term ideal of `I`).

We adopt the convention `⟨∅⟩ = {0}`, so `∅` is a Gröbner basis of the zero ideal.
-/
def IsGroebnerBasis (I : Ideal (MvPolynomial σ k)) (G : Finset (MvPolynomial σ k)) : Prop :=
  (∀ g ∈ G, g ≠ 0) ∧ GroebnerBasis_prop m I G

end MvPolynomial
