import Mathlib.RingTheory.MvPolynomial.Ideal
import Mathlib.RingTheory.MvPolynomial.MonomialOrder

variable {σ R : Type*} [CommSemiring R]

namespace MvPolynomial

variable (R) in
/--
#### Monomial ideal

An ideal `I ⊆ R[x_σ]` is called a **monomial ideal** if it is generated by monomials:
there exists a (possibly infinite) set `A` of exponent vectors such that
`I = ⟨ x^a | a ∈ A ⟩`.
-/
def monomialIdeal (s : Set (σ →₀ ℕ)) : Ideal (MvPolynomial σ R) :=
  Ideal.span ((fun a => monomial a (1 : R)) '' s)

end MvPolynomial
